### ISSUE TITLE
Clean README.md

### ISSUE THREAD

**Issue by ai** [collink/postcss-regions#1]
What main user cases for this plugin?

**Comment by collink** [comment]
The company I work for has a relatively complex, variable-driven SASS framework that we've developed in house.  The variables get us a good bit of the way a lot of times, but some of the designs we've gotten recently have required quite a bit of manual overrides (using more specific styles and `!important` flags in partials included after the base of the framework).

This isn't a problem, per se, but it causes a lot of extra CSS (the CSS generated by the base of the framework, followed by the CSS we write to override the default functionality of the base).  Often times, we find ourselves wishing we could just no-op an entire section and just re-style it from scratch.

We're evaluating PostCSS to replace SASS (we currently use a wrapper I wrote around `node-sass` that has a more customizable watcher, along with a couple other features), so I thought this might also be a good opportunity to tackle this problem in a less hacky way than trying to do it with mixins in SASS.

**Comment by ai** [comment]
Maybe you should show some better example. Right now most of users can’t uderstand how to use it.

**Comment by collink** [comment]
I intend to fix up README.md shortly.  I was just writing something quick to have something there.

**Comment by collink** [comment]
@ai If you'd like to see me add anything else, please let me know.  I'm closing this issue for now, but if you still don't feel the use-case and documentation are presented well enough, I'll address it again.  Thank you for your input.
